export const headphones = [
    {
        img: './img/assets/s8521.png',
        title: 'Apple BYZ S852I',
        price: 2927,
        sale: 3527,
        rate: 4.7,
        id: 1,
        quantity: 1,
    },
    {
        img: './img/assets/earpods1.png',
        title: 'Apple EarPods',
        price: 2327,
        sale: 0,
        rate: 4.5,
        id: 2,
        quantity: 1,
    },
    {
        img: './img/assets/earpods2.png',
        title: 'Apple EarPods',
        price: 2327,
        sale: 0,
        rate: 4.7,
        id: 3,
        quantity: 1,
    },
    {
        img: './img/assets/s8521.png',
        title: 'Apple BYZ S852I',
        price: 2927,
        sale: 0,
        rate: 4.7,
        id: 4,
        quantity: 1,
    },
    {
        img: './img/assets/earpods1.png',
        title: 'Apple EarPods',
        price: 2327,
        sale: 0,
        rate: 4.5,
        id: 5,
        quantity: 1,
    },
    {
        img: './img/assets/earpods2.png',
        title: 'Apple EarPods',
        price: 2327,
        sale: 0,
        rate: 4.5,
        id: 6,
        quantity: 1,
    },
]

export const wireless = [
    {
        img: './img/assets/airpods.png',
        title: 'Apple AirPods',
        price: 9527,
        sale: 0,
        rate: 4.7,
        id: 7,
        quantity: 1,
    },
    {
        img: './img/assets/gh-04.png',
        title: 'GERLAX GH-04',
        price: 6527,
        sale: 0,
        rate: 4.7,
        id: 8,
        quantity: 1,
    },
    {
        img: './img/assets/bo4.png',
        title: 'BOROFONE BO4',
        price: 7527,
        sale: 0,
        rate: 4.7,
        id: 9,
        quantity: 1,
    },
]
